export const ERROR_CODE = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  DATA_ROOM_NOT_FOUND: 'DATA_ROOM_NOT_FOUND',
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_RECIPIENT_NOT_FOUND: 'SHARE_RECIPIENT_NOT_FOUND',
  NAME_CONFLICT: 'NAME_CONFLICT',
  INVALID_UPLOAD: 'INVALID_UPLOAD',
  STORAGE_ERROR: 'STORAGE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
